# Generated by Django 2.2.4 on 2019-08-16 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500,
                                        unique=True, verbose_name='Url-адрес')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Дата добавления')),
                ('handled_at', models.DateTimeField(
                    null=True, verbose_name='Дата обработки')),
                ('timeshift', models.DurationField(
                    default=datetime.timedelta(0), verbose_name='До исполнения')),
                ('to_handle', models.BooleanField(
                    default=False, verbose_name='Ожидает исполнения')),
                ('title', models.CharField(blank=True,
                                           max_length=200, verbose_name='Заголовок')),
                ('heading', models.CharField(blank=True,
                                             max_length=400, null=True, verbose_name='Тег H1')),
                ('encoding', models.CharField(blank=True,
                                              max_length=40, verbose_name='Кодировка')),
                ('shed_at', models.DateTimeField(null=True)),
                ('task_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
